name:                adhoc-http
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/luntain/adhoc-http#readme
license:             BSD3
author:              Kamil Dworakowski
maintainer:          kamil@dworakowski.name
copyright:           2020 Kamil Dworakowski
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - snap-core
  - snap-server
  - random
  - uuid
  - bytestring
  - containers

executables:
  simple-http:
    source-dirs:      src
    main:             Main.hs
